[package]
name = "ruth"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true, features = ["std", "color", "help", "usage", "error-context", "suggestions", "derive", "env"] }
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio-rustls"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "fs"] }
tracing = { workspace = true, features = ["release_max_level_info"] }
tracing-subscriber = { workspace = true, features = ["fmt", "ansi"] }
axum = { workspace = true, features = ["tokio", "http1", "json"] }
argon2 = { workspace = true, features = ["password-hash", "std"] }
time = { workspace = true, features = ["serde", "formatting"] }
axum-extra = { workspace = true, features = ["cookie"] }
uuid = { workspace = true, features = ["v4", "serde"] }
tower-http = { workspace = true, features = ["trace"] }
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true, features = ["std"] }
migration = { path = "../../lib/migration" }
session = { path = "../../lib/session" }
entity = { path = "../../lib/entity" }
utils = { path = "../../lib/utils" }
bb8-redis = { workspace = true }
url = { workspace = true }
