[package]
name = "maid"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.32", default-features = false, features = ["macros", "rt-multi-thread"] }
trust-dns-server = {version = "0.23", default-features = false}
async-trait = "0.1"
anyhow = "1.0"
